# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1024)),
                ('min_length', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_length', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('counter_start', models.IntegerField(default=0)),
                ('counter_end', models.IntegerField(blank=True, null=True)),
                ('berth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marina.Berth')),
            ],
        ),
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('berth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marina.Berth')),
            ],
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1024)),
                ('code', models.CharField(db_index=True, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1024)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marina.Contract')),
            ],
        ),
        migrations.CreateModel(
            name='Marina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Pier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1024)),
                ('order', models.IntegerField(default=0)),
                ('double_site', models.BooleanField(default=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marina.Marina')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1024)),
                ('length', models.DecimalField(decimal_places=2, max_digits=6)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marina.Flag')),
            ],
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('berth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marina.Berth')),
                ('ship', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marina.Ship')),
            ],
        ),
        migrations.AddField(
            model_name='hub',
            name='pier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marina.Pier'),
        ),
        migrations.AddField(
            model_name='contract',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marina.Ship'),
        ),
        migrations.AddField(
            model_name='connector',
            name='hub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marina.Hub'),
        ),
        migrations.AddField(
            model_name='connection',
            name='connector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marina.Connector'),
        ),
        migrations.AddField(
            model_name='connection',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marina.Ship'),
        ),
        migrations.AddField(
            model_name='berth',
            name='pier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marina.Pier'),
        ),
    ]
