# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='date_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leave',
            name='date_start',
            field=models.DateField(),
        ),
    ]
