# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0002_auto_20160705_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='YBom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('pier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marina.Pier')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
