# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0003_ybom'),
    ]

    operations = [
        migrations.AddField(
            model_name='ybom',
            name='left',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
