# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-27 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0004_ybom_left'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connection',
            options={'ordering': ['counter_start', '-counter_end']},
        ),
        migrations.RemoveField(
            model_name='connection',
            name='place',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='ship',
        ),
        migrations.AddField(
            model_name='connection',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marina.Contract'),
        ),
        migrations.AddField(
            model_name='connection',
            name='stay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marina.Stay'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contact_email',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='contact_name',
            field=models.CharField(blank=True, db_index=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='contact_phone',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='stay',
            name='contact_email',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='stay',
            name='contact_name',
            field=models.CharField(blank=True, db_index=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='stay',
            name='contact_phone',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='stay',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marina.Ship'),
        ),
    ]
