# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-28 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0005_auto_20160727_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='notices',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='stay',
            name='notices',
            field=models.TextField(default=''),
        ),
    ]
